#!/usr/bin/python3
# -*- coding: utf-8 -*-

""" Feedex main executable """

import sys

PLATFORM = sys.platform
if PLATFORM == 'linux': sys.path.append('/usr/share/feedex/feedex')
else: 
    sys.stderr.write(f'Platform {PLATFORM} not supported... Aborting...')
    sys.exit(1)

from feedex_headers import *









def main():
 
    action = None
    argument = None
    argument2 = None
    argument3 = None

    params = {}
    fdx.cli = True
    fdx.single_run = True

    config_file = os.getenv('FEEDEX_CONFIG', None)
    database = os.getenv('FEEDEX_DB_PATH', None)
    log_file = os.getenv('FEEDEX_LOG', None)

    query = False
    cli_display = False

    # Command line argument parsing...
    if len(sys.argv) > 1:

        for i, arg in enumerate(sys.argv):

            if i == 0: continue

            if arg in ('-h', '--help', '--usage'):
                from feedex_docs import FEEDEX_SHORT_HELP
                mu_print(FEEDEX_SHORT_HELP)
                return 0
            elif arg in ('-hh', '--help-long'):
                from feedex_docs import FEEDEX_LONG_HELP
                mu_print(FEEDEX_LONG_HELP)
                return 0
            elif arg == ('--help-feeds'):
                from feedex_docs import FEEDEX_HELP_FEEDS
                mu_print(FEEDEX_HELP_FEEDS)
                return 0
            elif arg == ('--help-query'):
                from feedex_docs import FEEDEX_HELP_QUERY
                mu_print(FEEDEX_HELP_QUERY)
                return 0
            elif arg == ('--help-categories'):
                from feedex_docs import FEEDEX_HELP_FEEDS
                mu_print(FEEDEX_HELP_FEEDS)
                return 0
            elif arg == ('--help-entries'):
                from feedex_docs import FEEDEX_HELP_ENTRIES
                mu_print(FEEDEX_HELP_ENTRIES)
                return 0
            elif arg == ('--help-rules'):
                from feedex_docs import FEEDEX_HELP_RULES
                mu_print(FEEDEX_HELP_RULES)
                return 0
            elif arg == ('--help-scripting'):
                from feedex_docs import FEEDEX_HELP_SCRIPTING, FEEDEX_HELP_JSON_QUERY
                mu_print(FEEDEX_HELP_SCRIPTING)
                mu_print(FEEDEX_HELP_JSON_QUERY)
                return 0
            elif arg == ('--help-examples'):
                from feedex_docs import FEEDEX_HELP_EXAMPLES
                mu_print(FEEDEX_HELP_EXAMPLES)
                return 0
                

            elif arg in ('-v', '--version'):
                print(f"{FEEDEX_VERSION}")
                return 0

            elif arg in ('--about',):
                mu_print(FEEDEX_HELP_ABOUT)
                return 0


            # read parameters and actions... uses utilities from feedex_utils.py for clean parsing and sanity checks

            #PARAMETERS
            elif arg.startswith('--config='): config_file = fdx.get_par(arg)
            elif arg.startswith('--log='): log_file = fdx.get_par(arg)
            elif arg.startswith('--database='): database = fdx.get_par(arg)

            elif arg == '--debug': fdx.debug_level = 1
            elif arg.startswith('--debug='): fdx.debug_level = abs(scast(fdx.get_par(arg), int, 0))

            #DISPLAY 
            elif arg == '--csv': params['output']='csv'
            elif arg == '--json': params['output']='json'
            elif arg == '--export': params['output']='json_dict'
            elif arg == '--long': params['output']='long'
            elif arg == '--headlines': params['output']='headlines'

            elif arg.startswith('--display-cols='): params['display_cols'] = fdx.get_par(arg)
            
            elif arg.startswith('--ofile='): params['ofile'] = fdx.get_par(arg)
            elif arg.startswith('--export='):
                params['output']='json_dict'                
                params['ofile'] = fdx.get_par(arg)


            elif arg == '--silent': fdx.cli=False

            elif arg == '--clipboard': params['clipboard'] = True

            elif arg.startswith('--delimiter='): params['delimiter'] = fdx.get_par(arg)
            elif arg.startswith('--delimiter2='): params['delimiter2'] = fdx.get_par(arg)
            elif arg.startswith('--escape='): params['delim_escape'] = fdx.get_par(arg)

            elif arg.startswith('--note_marker='): params['note_marker'] = fdx.get_par(arg)
            elif arg.startswith('--read_marker='): params['read_marker'] = fdx.get_par(arg)

            elif arg.startswith('--bold_beg='): params['bold_beg'] = fdx.get_par(arg)
            elif arg.startswith('--bold_end='): params['bold_end'] = fdx.get_par(arg)

            elif arg.startswith('--trunc='): params['trunc'] = fdx.get_par(arg)

            elif arg == '--desktop-notify':
                params['desktop_notify'] = True
                query = True
                fdx.cli = False


	        #NEWS		
            elif arg in ('-g','--get-news'):
                action = 'get_news'
                argument = slist(sys.argv, i+1, None)
                break

            elif arg in ('-c','--check'):
                action = 'check'
                argument = slist(sys.argv, i+1, None)
                break

            elif arg in ('-o','--open-in-browser'):
                action = 'open'
                argument = slist(sys.argv, i+1, None)
                break		



            #FEEDS
            elif arg in ('-L','--list-feeds'):
                action = 'list_feeds'
                query = True
                break

            elif arg == '--list-feeds-cats':
                action = 'list_feeds_cats'
                query = True
                break

            elif arg in ('-a','--add-feed'):
                action = 'add_url'
                argument = slist(sys.argv, i+1, None)
                break

            elif arg in ('-u', '--update-feeds'):
                action = 'update_feeds'
                argument = slist(sys.argv, i+1, None)
                break
			
            elif arg in ('-D','--delete-feed'):
                action = 'del_feed'
                argument = slist(sys.argv, i+1, None)
                break

            elif arg in ('-F','--read-feed'):
                action = 'read_feed'
                query = True
                argument = slist(sys.argv, i+1, None)
                break	

            elif arg in ('-C','--read-category'):
                action = 'read_category'
                query = True
                argument = slist(sys.argv, i+1, None)
                break	

            elif arg == '--examine-feed':
                action = 'examine_feed'
                cli_display = True
                argument = slist(sys.argv, i+1, None)
                break	

            elif arg == '--edit-feed':
                action = 'edit_feed'
                argument, argument2, argument3 = slist(sys.argv, i+1, None), slist(sys.argv, i+2, None), slist(sys.argv, i+3, None)
                break

            elif arg == '--insert-feed-before':
                action = 'insert_feed_before'
                argument, argument2 = slist(sys.argv, i+1, None), slist(sys.argv, i+2, None)
                break

            elif arg == '--test-regexes':
                action = 'test_regexes'
                cli_display = True
                argument = slist(sys.argv, i+1, None)
                break


            #ENTRIES			
            elif arg in ('-r','--read-entry'):
                action = 'read_entry'
                cli_display = True
                argument = slist(sys.argv, i+1, None)
                break
            elif arg in ('-S','--find-similar'):
                action = 'similar'
                query = True
                argument = slist(sys.argv, i+1, None)
                break

            elif arg == '--mark':
                action = 'mark'
                argument, argument2 = slist(sys.argv, i+1, None), slist(sys.argv, i+2, None)
                break	

            elif arg == '--unmark':
                action = 'mark'
                argument, argument2 = slist(sys.argv, i+1, None), 0
                break	

            elif arg == '--flag':
                action = 'flag'
                argument, argument2 = slist(sys.argv, i+1, None), slist(sys.argv, i+2, None)
                break	

            elif arg == '--edit-entry':
                action = 'edit_entry'
                argument, argument2, argument3 = slist(sys.argv, i+1, None), slist(sys.argv, i+2, None), slist(sys.argv, i+3, None)
                break	

                	
            elif arg in ('--add-entry','-N'):
                action='add_entry'
                argument, argument2 = slist(sys.argv, i+1, None), slist(sys.argv, i+2, None)
                break

            elif arg == '--import-entries-from-file':
                action='import_entries_from_file'
                argument = slist(sys.argv, i+1, None)
                break

            elif arg == '--import-entries-from-pipe':
                action='import_entries_from_pipe'
                break

            elif arg == '--delete-entry':
                action = 'del_entry'
                argument = slist(sys.argv, i+1, None)
                break
	
            # ITEM RESTORES
            elif arg == '--restore-feed':
                action = 'restore_feed'
                argument = slist(sys.argv, i+1, None)
                break
            elif arg == '--restore-category':
                action = 'restore_category'
                argument = slist(sys.argv, i+1, None)
                break
            elif arg == '--restore-entry':
                action = 'restore_entry'
                argument = slist(sys.argv, i+1, None)
                break


            #QUERIES
            elif arg in ('-q','--query'):
                action = 'query_entries'
                query = True
                argument = slist(sys.argv, i+1, None)
                break
			


            #KEYWORDS, HISTORY, FETCHES AND RULES
            elif arg == '--list-rules':
                action = 'list_rules'
                query = True
                break
            elif arg == '--list-learned-terms':
                action = 'list_learned_terms'
                query = True
                break

            elif arg == '--list-history':
                action = 'list_history'
                query = True
                break	

            elif arg == '--list-fetches':
                action = 'list_fetches'
                query = True
                break	
            

            elif arg == '--add-rule':
                action = 'add_rule'
                argument = slist(sys.argv, i+1, None)
                break	
            elif arg == '--add-regex':
                action = 'add_regex'
                argument = slist(sys.argv, i+1, None)
                break	
            elif arg == '--add-stemmed':
                action = 'add_stemmed'
                argument = slist(sys.argv, i+1, None)
                break	

            elif arg == '--edit-rule':
                action = 'edit_rule'
                argument, argument2, argument3 = slist(sys.argv, i+1, None), slist(sys.argv, i+2, None), slist(sys.argv, i+3, None)
                break	

            elif arg == '--delete-rule':
                action = 'del_rule'
                argument = slist(sys.argv, i+1, None)
                break	


            elif arg == '--term-net':
                action = 'term_net'
                argument = slist(sys.argv, i+1, None)
                query = True
                break	

            elif arg == '--context':
                action = 'context'
                argument = slist(sys.argv, i+1, None)
                query = True
                break	

            elif arg == '--time-series':
                action = 'time_series'
                argument = slist(sys.argv, i+1, None)
                query = True
                break	

            elif arg == '--trends':
                action = 'trends'
                argument = slist(sys.argv, i+1, None)
                query = True
                break	
            
            elif arg == '--trending':
                action = 'trending'
                argument = slist(sys.argv, i+1, None)
                query = True
                break	

            elif arg in ('-R', '--recommend',):
                action = 'recom'
                query = True
                break	


            elif arg == '--rel-in-time':
                action = 'rel_in_time'
                argument = slist(sys.argv, i+1, None)
                query = True
                break	



            #CATEGORIES
            elif arg == '--list-categories':
                action = 'list_categories'
                query = True
                break
            elif arg == '--add-category':
                action = 'add_category'
                argument, argument2 = slist(sys.argv, i+1, None), slist(sys.argv, i+2, None)
                break
            elif arg == '--delete-category':
                action = 'del_category'
                argument = slist(sys.argv, i+1, None)
                break
            elif arg == '--edit-category':
                action = 'edit_category'
                argument, argument2, argument3 = slist(sys.argv, i+1, None), slist(sys.argv, i+2, None), slist(sys.argv, i+3, None)
                break


            #FLAGS
            elif arg == '--list-flags':
                action = 'list_flags'
                query = True
                break
            elif arg == '--add-flag':
                action = 'add_flag'
                argument, argument2 = slist(sys.argv, i+1, None), slist(sys.argv, i+2, None)
                break
            elif arg == '--delete-flag':
                action = 'del_flag'
                argument = slist(sys.argv, i+1, None)
                break
            elif arg == '--edit-flag':
                action = 'edit_flag'
                argument, argument2, argument3 = slist(sys.argv, i+1, None), slist(sys.argv, i+2, None), slist(sys.argv, i+3, None)
                break
            


            #MAINTENANCE
            elif arg == '--clear-history':
                action = 'clear_history'
                break
            elif arg == '--delete-query-rules':
                action = 'delete_query_rules'
                break
            elif arg == '--delete-learned-terms':
                action = 'delete_learned_terms'
                break
            elif arg == '--empty-trash':
                action = 'empty_trash'
                break

            elif arg  == '--reindex':
                action = 'reindex'
                argument = slist(sys.argv, i+1, None)
                break	
            elif arg == '--rerank':
                action = 'rerank'
                argument = slist(sys.argv, i+1, None)
                break	
            elif arg == '--relearn':
                action = 'relearn'
                argument = slist(sys.argv, i+1, None)
                break

            elif arg.startswith('--batch-size='): params['batch_size'] = fdx.get_par(arg, cast=int, default=1500)

            # Data transfer
            elif arg == '--import-feeds':
                action = 'import_feeds'
                argument = slist(sys.argv, i+1, None)
                break
            elif arg == '--import-rules':
                action = 'import_rules'
                argument = slist(sys.argv, i+1, None)
                break
            elif arg == '--import-flags':
                action = 'import_flags'
                argument = slist(sys.argv, i+1, None)
                break

            elif arg == '--export-feeds':
                action = 'export_feeds'
                query = True
                argument = slist(sys.argv, i+1, None)
                break
            elif arg == '--export-rules':
                action = 'export_rules'
                query = True
                argument = slist(sys.argv, i+1, None)
                break
            elif arg == '--export-flags':
                action = 'export_flags'
                query = True
                argument = slist(sys.argv, i+1, None)
                break



            elif arg == '--download-catalog':
                action = 'download_catalog'
                argument = slist(sys.argv, i+1, None)
                break

            elif arg in ('-qc', '--query-catalog'):
                action = 'query_catalog'
                argument = slist(sys.argv, i+1, None)
                break

            elif arg == '--import-from-catalog':
                action = 'import_from_catalog'
                argument = slist(sys.argv, i+1, None)
                break


            #DATABASE
            elif arg == '--create-db':
                action = 'create_db'
                break
            
            elif arg == '--defaults': params['defaults'] = True
            elif arg == '--default-feeds': params['default_feeds'] = True

            elif arg == '--db-maintenance':
                action = 'db_maintenance'	
                break

            elif arg == '--lock-db':
                action = 'lock'
                break
            elif arg == '--unlock-db':
                action = 'unlock'
                break
            elif arg == '--db-stats':
                action = 'db_stats'
                cli_display = True
                break
            
            elif arg.startswith('--timeout='): params['timeout'] = fdx.get_par(arg)

            #Additional parameter (non-action)
            # Params for adding entries
            elif arg.startswith('--limit='): params['limit'] = fdx.get_par(arg)

            elif arg == '--learn': params['learn'] = True
            elif arg == '--no-learn': params['learn'] = False

            elif arg == '--no-fetch': params['no_fetch'] = True
                        
            # Parameters for searching entries et al.
            elif arg  == '--json_query': params['json_query'] = True

            elif arg.startswith('--lang='): params['lang'] = fdx.get_par(arg)
            elif arg.startswith('--weight='): params['weight'] = fdx.get_par(arg)
            elif arg.startswith('--handler='): params['handler'] = fdx.get_par(arg)
            elif arg.startswith('--field='): params['field'] = fdx.get_par(arg)
            elif arg.startswith('--type='): params['qtype'] = fdx.get_par(arg)
            elif arg.startswith('--logic='): params['logic'] = fdx.get_par(arg)

            elif arg.startswith('--from='): params['date_from'] = fdx.get_par(arg)
            elif arg.startswith('--to='): params['date_to'] = fdx.get_par(arg)

            elif arg.startswith('--added_from='): params['date_add_from'] = fdx.get_par(arg)
            elif arg.startswith('--added_to='): params['date_add_to'] = fdx.get_par(arg)

            elif arg.startswith('--feed='): params['feed'] = fdx.get_par(arg)
            elif arg.startswith('--category='): params['category'] = fdx.get_par(arg)
            elif arg.startswith('--parent_category='): params['parent_category'] = fdx.get_par(arg)
            elif arg.startswith('--parent_id='): params['parent_id'] = fdx.get_par(arg)
            elif arg.startswith('--feed_id='): params['feed_id'] = fdx.get_par(arg)

            elif arg == '--note': params['note'] = 1
            elif arg == '--news': params['note'] = 0
    
            elif arg == '--case_ins': params['case_ins'] = True
            elif arg == '--case_sens': params['case_sens'] = True

            elif arg == '--last': params['last'] = True
            elif arg.startswith('--last_n='): params['last_n'] = fdx.get_par(arg)
            elif arg == '--today': params['today']=True
            elif arg == '--last_week': params['last_week']=True
            elif arg == '--last_month': params['last_month']=True
            elif arg == '--last_quarter': params['last_quarter']=True
            elif arg == '--last_six_months': params['last_six_months']=True
            elif arg == '--last_year': params['last_year']=True
            elif arg == '--last_hour': params['last_hour']=True

            elif arg == '--read': params['read']=True
            elif arg == '--unread': params['unread']=True
            
            elif arg.startswith('--flag='): params['flag'] = fdx.get_par(arg)

            elif arg == '--deleted': params['deleted']=True

            elif arg == '--rev': params['rev']=True

            elif arg.startswith('--sort='): params['sort'] = fdx.get_par(arg)
            
            elif arg.startswith('--page='): params['page'] = fdx.get_par(arg)
            elif arg.startswith('--page_len='): params['page_len'] = fdx.get_par(arg)

            elif arg == '--plot': params['plot']=True
            elif arg.startswith('--term-width='): params['term_width'] = fdx.get_par(arg)

            elif arg.startswith('--group='): params['group'] = fdx.get_par(arg)
            elif arg.startswith('--depth='): params['depth'] = fdx.get_par(arg)
            
            elif arg.startswith('--summarize='): params['summarize'] = fdx.get_par(arg)
            elif arg == '--details': params['details'] = True


            elif arg in ('--gui','--GUI'):
                action = 'GUI'
                break

            elif arg in ('--sql'):
                action = 'execute_SQL'
                argument = slist(sys.argv, i+1, None)
                break

            elif arg == '--test':
                action = 'test'
                break

            else: fdx.cli_param_error = True
                            
    else:
        # If no args are given - run GUI (not supported(yet?) :)
        action="GUI"


    if fdx.cli_param_error: return msg(FX_ERROR_CL,_("""Invalid arguments given...
Make sure that:
 - parameters are before actions
 - every parameter and action is available
 
 """) )




    # Config stuff...
    config_file = coalesce(config_file, FEEDEX_CONFIG)
    if not os.path.isfile(config_file): 
        msg(_('Config file %a not found. Using default...'), config_file)
        copyfile( FEEDEX_SYS_CONFIG, FEEDEX_CONFIG )
        config_file = FEEDEX_CONFIG

    fdx.parse_config(config_file)

    fdx.config['log'] = coalesce(log_file, fdx.config.get('log'), os.path.join(FEEDEX_SHARED_PATH, 'feedex.log') )
    fdx.config['db_path'] = coalesce(database, fdx.config.get('db_path'), os.path.join(FEEDEX_SHARED_PATH, 'feedex.db') )
    fdx.config['use_keyword_learning'] = coalesce(params.get('learn'), fdx.config.get('use_keyword_learning'), True)
    fdx.config['timeout'] = coalesce(params.get('timeout'), fdx.config.get('timeout'), 0)

    # Validate configuration
    if action == 'GUI': fdx.validate_config(load=True, strict=False)
    else: 
        err = fdx.validate_config(load=True, strict=True)
        if err != 0: return msg(*err)

    # Install locale
    if fdx.config.get('lang') not in (None,'en'):
        lang = gettext.translation('feedex', languages=[fdx.config.get('lang')])
        lang.install(FEEDEX_LOCALE_PATH)

    # Check and create needed dirs
    check_paths((FEEDEX_SHARED_PATH,))

    # Lazy load and run GUInterface
    if action == 'GUI':

        # GUI display ... 
        if fdx.debug_level in (None,0): fdx.cli = False
        fdx.single_run = False
        
        from feedex_gui_main import feedex_run_main_win, FeedexMainWin
        feedex_run_main_win(**params)
        return 0


    # Create database if specified
    if action == 'create_db':
        feedex = FeedexDatabase(db_path=fdx.config['db_path'], config=fdx.config, allow_create=True, main_conn=True, **params)
        try: feedex.connect(defaults=params.get('defaults',False), default_feeds=params.get('default_feeds', False))
        except (FeedexDatabaseError, FeedexDataError,) as e: return e.code

        if not feedex.created:
            msg(_('Database %a already exists...'), fdx.config['db_path'])
            feedex.close()
        return 0

    # Building catalog (dev)
    if action == 'download_catalog':
        catalog = FeedexCatalog()
        err = catalog.build_catalog(odir=argument)
        return err

    # Searching feed catalog
    elif action == 'query_catalog':
        Q = FeedexCatalogQuery()
        err = Q.query(argument, {'field':params.get('field'), 'category':params.get('category')})
        feedex_cli = FeedexCLI(**params)
        if err == 0: feedex_cli.out_table(Q)
        return err


    # Init the main workhorse ...
    feedex = FeedexDatabase(db_path=fdx.config['db_path'], config=fdx.config, allow_create=False, main_conn=True, **params)
    try: 
        if action == 'unlock': 
            feedex.connect(unlock=True)
            return 0
        elif action == 'lock': 
            feedex.connect(lock=True)
            return 0
        else: feedex.connect()
    except FeedexDatabaseLockedError as e:
        return e.code
    except (FeedexDatabaseNotFoundError,) as e:
        return msg(e.code, _('Use feedex --database=[PATH_TO_DB] [--defaults, --default-feeds] --create-db to create new Database'))
    except (FeedexDatabaseError, FeedexDataError,) as e: return e.code


    # Lazy load desktop notification support
    if params.get('desktop_notify',False) and action in ('get_news','check','query_entries','add_entry','add_rule','add_regex','add_stemmed',):

        from feedex_desktop_notifier import DesktopNotifier
        feedex.load_icons()
        desktop_notifier = DesktopNotifier(icons=fdx.icons_cache)

    # Lazy load clipboard support. Substitute arguments with clipboard selection
    if params.get('clipboard',False) and ('add_entry','add_rule','add_regex','add_full_text',):
            
        from feedex_clipper import FeedexClipper
        feedex.load_icons()
        clipper = FeedexClipper(config=fdx.config)

        argument, argument2 = clipper.process_args(argument, argument2)

        if clipper.error is not None:
            if params.get('desktop_notify',False): desktop_notifier.notify(clipper.error, None, -1)
            return FX_ERROR

    # Init query object
    if query: feedex.connect_QP()
    if query or cli_display:
        feedex_cli = FeedexCLI(**params)
        if params.get('desktop_notify',False): feedex_cli.connect_DN(desktop_notifier)


    # Wrapper for notifications
    def do_notify():
        if feedex.new_items > 0:
            if params.get('desktop_notify', False): 
                params['last'] = True
                feedex.connect_QP()
                err = feedex.Q.query('', params, rank=True, snippets=False, allow_group=True)
                if err == 0: feedex_cli.out_table(feedex.Q)

    # Check if query input is a JSON string and parse it
    if params.get('json_query',False) and action in ('query_entries', 'term_net', 'time_series', 'context', 'similar', 'trends', 'trending', 'rel_in_time', 'recom',):
        argument, filters = feedex.Q.parse_json_query(argument)
        if argument == -1: action = None
        # Replace relevant keys for parameters
        for k,v in filters.items():
            if k != 'phrase': params[k] = v








    # Execute actions specified on the command line. Looks a bit convoluted, but it is not that complicated, really
    # All of the following are described in long help

    if action == 'get_news':
        feedex.fetch(id=argument, force=True, ignore_interval=True)
        do_notify()

    elif action == 'check':
        feedex.fetch(id=argument, force=False, ignore_interval=False)
        do_notify()

    elif action == 'open':
        if argument.isdigit(): entry = FeedexEntry(feedex, id=argument)
        else: entry = FeedexEntry(feedex, url=argument)
        entry.open(background=False)

        

    elif action == 'list_feeds':
        err = feedex.Q.list_feeds(feeds_only=True)
        if err == 0: feedex_cli.out_table(feedex.Q)

    elif action == 'add_url':
        feed = FeedexFeed(feedex)
        params['url'] = argument

        if params.get('desktop_notify',False): desktop_notifier.notify(_("Adding Channel from URL ..."), 0)
        err = feed.add_from_url(new=params, no_fetch=params.get('no_fetch',False), handler=params.get('handler'))

        if params.get('desktop_notify',False):
            if clipper.error is None and err == 0: desktop_notifier.notify(_("Channel successfully added!"), None, feed.vals.get('id',-2))
            else: desktop_notifier.notify(_("Error adding new Channel!"), None, -1)


    elif action == 'update_feeds':
        feedex.fetch(id=argument, force=True, ignore_interval=True, update_only=True)
    elif action == 'del_feed':
        feed = FeedexFeed(feedex, feed_id=argument)
        feed.delete()
    elif action == 'edit_feed':
        feed = FeedexFeed(feedex, feed_id=argument)
        idict = {argument2 : argument3}
        # Prompt for auth data
        if argument2 == 'auth' and argument3 not in ('NONE','NULL'):
            from getpass import getpass
            idict['domain'] = nullif( input(_("Enter domain for authentication (NONE for empty): ")), '')
            idict['login'] = nullif( input(_("Enter login: ")), '')
            idict['passwd'] = nullif( getpass(prompt=_("Enter password: ")), '')

        feed.update(idict)

    elif action == 'insert_feed_before':
        feed = FeedexFeed(feedex, feed_id=argument)
        feed.order_insert(argument2, with_cat=False)

    elif action == 'read_feed':
        params['feed'] = argument
        params['fallback_sort'] = 'pubdate'
        err = feedex.Q.query('', params, rank=False, cnt=False, snippets=False)
        if err == 0: feedex_cli.out_table(feedex.Q)

    elif action == 'read_category':
        params['category'] = argument
        params['fallback_sort'] = 'pubdate'
        err = feedex.Q.query('', params, rank=False, cnt=False, snippets=False)
        if err == 0: feedex_cli.out_table(feedex.Q)
    
    elif action == 'examine_feed':
        feed = FeedexFeed(feedex, feed_id=argument)
        feedex_cli.out_feed(feed)
    
    elif action == 'test_regexes':
        feed = FeedexFeed(feedex, feed_id=argument)
        feedex_cli.out_test_regex(feed)

		
    elif action == 'read_entry':
        entry = FeedexEntry(feedex, id=argument)
        feedex_cli.out_entry(entry, **params)

    elif action == 'similar':
        err = feedex.Q.similar(argument, params)
        if err == 0: feedex_cli.out_table(feedex.Q)
    elif action == 'mark':
        entry = FeedexEntry(feedex, id=argument)
        entry.update({'read': argument2})
    elif action == 'flag':
        entry = FeedexEntry(feedex, id=argument)
        entry.update({'flag': argument2})
    elif action == 'edit_entry':
        entry = FeedexEntry(feedex, id=argument)
        entry.update({argument2: argument3})
    elif action == 'add_entry':
        entry = FeedexEntry(feedex)
        params['title'] = argument
        params['desc'] = argument2
        if params.get('weight') is not None: params['read'] = scast(params.get('weight'), int, 0)

        if params.get('desktop_notify',False): desktop_notifier.notify(_("Adding new Entry..."), None, 0)

        entry.add(new=params)

        if params.get('desktop_notify',False):
            if clipper.error is None and fdx.ret_status == 0: desktop_notifier.notify(_("Entry successfully added!"), None, entry.vals.get('feed_id',-2))
            else: desktop_notifier.notify(_("Error adding new entry!"), None, -1)

    elif action == 'del_entry':
        entry = FeedexEntry(feedex, id=argument)
        entry.delete()



    # Main query
    elif action == 'query_entries': 
        err = feedex.Q.query(argument, params, json_file=params.get('json_file'), rank=True, snippets=True, allow_group=True)
        if err == 0: feedex_cli.out_table(feedex.Q)



    elif action == 'list_rules': 
        err = feedex.Q.list_rules()
        if err == 0: feedex_cli.out_table(feedex.Q)

    elif action == 'list_learned_terms':
        err = feedex.Q.list_learned_terms()
        if err == 0: feedex_cli.out_table(feedex.Q)

    elif action == 'list_history': 
        err = feedex.Q.list_history()
        if err == 0: feedex_cli.out_table(feedex.Q)

    elif action == 'add_rule':
        rule = FeedexRule(feedex)
        params['string'] = argument
        params['type'] = 0
        if params.get('desktop_notify',False): desktop_notifier.notify(_("Adding new Rule..."), None, 0)
        rule.add(new=params)
        if params.get('desktop_notify',False):
            if clipper.error is None and feedex.MC.ret_status == 0: desktop_notifier.notify(_("Rule successfully added!"), None, -2)
            else: desktop_notifier.notify(_("Error adding new Rule!"), None, -1)

    elif action == 'add_regex':
        rule = FeedexRule(feedex)
        params['string'] = argument
        params['type'] = 2
        if params.get('desktop_notify',False): desktop_notifier.notify(_("Adding new REGEX Rule..."), None, 0)
        rule.add(new=params)
        if params.get('desktop_notify',False):
            if clipper.error is None and feedex.MC.ret_status == 0: desktop_notifier.notify(_("REGEX successfully added!"), None, -2)
            else: desktop_notifier.notify(_("Error adding new REGEX!"), None, -1)

    elif action == 'add_stemmed':
        rule = FeedexRule(feedex)
        params['string'] = argument
        params['type'] = 1
        if params.get('desktop_notify',False): desktop_notifier.notify(_("Adding new Stemmed Rule..."), None, 0)
        rule.add(new=params)
        if params.get('desktop_notify',False):
            if clipper.error is None and feedex.MC.ret_status == 0: desktop_notifier.notify(_("Stemmed Rule successfully added!"), None, -2)
            else: desktop_notifier.notify(_("Error adding new Stemmed Rule!"), None, -1)




    elif action == 'edit_rule':
        rule = FeedexRule(feedex, id=argument)
        rule.update({argument2: argument3})
    elif action == 'del_rule':
        rule = FeedexRule(feedex, id=argument)
        rule.delete()


    elif action == 'term_net':
        err = feedex.Q.term_net(argument, params)
        if err == 0: feedex_cli.out_table(feedex.Q)
    elif action == 'time_series':
        err = feedex.Q.time_series(argument, params)
        if err == 0: feedex_cli.out_table(feedex.Q)
    elif action == 'rel_in_time':
        err = feedex.Q.relevance_in_time(argument, params)
        if err == 0: feedex_cli.out_table(feedex.Q)
    elif action == 'context':
        err = feedex.Q.context(argument, params)
        if err == 0: feedex_cli.out_table(feedex.Q)
    elif action == 'trends':
        err = feedex.Q.trends(argument, params)
        if err == 0: feedex_cli.out_table(feedex.Q)
    elif action == 'recom':
        err = feedex.Q.recommend(params)
        if err == 0: feedex_cli.out_table(feedex.Q)
    elif action == 'trending':
        err = feedex.Q.trending(argument, params)
        if err == 0: feedex_cli.out_table(feedex.Q)


    elif action == 'list_categories':
        if feedex_cli.output in ('cli',None): feedex_cli.output = 'notes'
        err = feedex.Q.list_feeds(cats_only=True)
        if err == 0: feedex_cli.out_table(feedex.Q)
    elif action == 'list_feeds_cats':
        if feedex_cli.output in ('cli',None): feedex_cli.output = 'headlines'
        err = feedex.Q.feed_tree()
        if err == 0: feedex_cli.out_table(feedex.Q)    
    elif action == 'add_category':
        feed = FeedexFeed(feedex)
        feed.add(new={'title':argument, 'name': argument, 'subtitle':argument2, 'is_category':True})
    elif action == 'del_category':
        feed = FeedexFeed(feedex, category_id=argument)
        feed.delete()
    elif action == 'edit_category':
        feed = FeedexFeed(feedex, category_id=argument)
        feed.update({argument2: argument3})

    elif action == 'list_flags':
        err = feedex.Q.list_flags()
        if err == 0: feedex_cli.out_table(feedex.Q)
    elif action == 'add_flag':
        flag = FeedexFlag(feedex)
        flag.add(new={'name':argument, 'desc': argument2})
    elif action == 'del_flag':
        flag = FeedexFlag(feedex, id=argument)
        flag.delete()
    elif action == 'edit_flag':
        flag = FeedexFlag(feedex, id=argument)
        flag.update({argument2: argument3})

    elif action == 'list_fetches':
        err = feedex.Q.list_fetches()
        if err == 0: feedex_cli.out_table(feedex.Q)


    elif action == 'restore_feed':
        feed = FeedexFeed(feedex, feed_id=argument)
        feed.update({'deleted': 0})
    elif action == 'restore_category':
        feed = FeedexFeed(feedex, category_id=argument)
        feed.update({'deleted': 0})
    elif action == 'restore_entry':
        entry = FeedexEntry(feedex, id=argument)
        entry.update({'deleted': 0})

    elif action == 'clear_history': feedex.clear_history()
    elif action == 'delete_learned_terms': feedex.delete_learned_terms()
    elif action == 'empty_trash': feedex.empty_trash()
        


    elif action in ('reindex','rerank','relearn'):
        # Parse argument for ID or id ranges for mass recalculating        
        start_id = None
        end_id = None
        if type(argument) is str and '-' in argument:
            argl = argument.split('-')
            start_id = scast( slist(argl,0, None), int, None)
            end_id = scast( slist(argl,1, None), int, None)
            if start_id is None and end_id is None:
                sys.stderr.write(_("Could not resolve id range! Should be in format: NN-NN"))
                return FX_ERROR_CL
        else:
            argument = scast(argument, int, None)


        if action == 'reindex': feedex.recalculate(id=argument, batch_size=params.get('batch_size'), start_id=start_id, end_id=end_id, index=True, rank=False, learn=False)
        elif action == 'rerank': feedex.recalculate(id=argument, batch_size=params.get('batch_size'), start_id=start_id, end_id=end_id, rank=True, learn=False, index=False)
        elif action == 'relearn': feedex.recalculate(id=argument, batch_size=params.get('batch_size'), start_id=start_id, end_id=end_id, rank=False, learn=True, index=False)




    elif action == 'export_feeds':
        feedex.Q.list_feeds(all=True)
        feedex_cli.output = 'json_dict'
        feedex_cli.ofile = argument
        feedex_cli.out_table(feedex.Q)

    elif action == 'export_rules':
        feedex.Q.list_rules()
        feedex_cli.output = 'json_dict'
        feedex_cli.ofile = argument
        feedex_cli.out_table(feedex.Q)

    elif action == 'export_flags':
        feedex.Q.list_flags()
        feedex_cli.output = 'json_dict'
        feedex_cli.ofile = argument
        feedex_cli.out_table(feedex.Q)


    elif action == 'import_entries_from_file': feedex.import_entries(efile=argument, learn=params.get('learn',True))
    elif action == 'import_entries_from_pipe': feedex.import_entries(pipe=True, learn=params.get('learn',True))

    elif action == 'import_feeds': feedex.import_feeds(argument)
    elif action == 'import_rules': feedex.import_rules(argument)
    elif action == 'import_flags': feedex.import_flags(argument)
    

    elif action == 'import_from_catalog':
        catalog = FeedexCatalog(db=feedex)
        catalog.prep_import(argument)
        if catalog.queue_len > 0: catalog.do_import()


    elif action == 'db_maintenance': feedex.maintenance()

    elif action == 'db_stats': feedex_cli.out_db_stats(feedex.stats())


    elif action == 'execute_SQL' and fdx.debug_level not in (None, 0):
        print(_('Executing SQL statement...'))
        feedex.curs.execute(argument)
        feedex.conn.commit()
        print(_('Done.'))



    elif action == 'test' and fdx.debug_level not in (None,0):
        pass



    # Formalities...
    feedex.close()

    return fdx.ret_status



        	



if __name__ == '__main__':
    ret_status = main() 
    sys.exit(abs(ret_status))


